apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-web
  name: roar-web
  namespace: roar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roar-web
  template:
    metadata:
      labels:
        app: roar-web
    spec:
      containers:
      - image: localhost:5000/roar-web:1.0.0
        imagePullPolicy: Always
        name: roar-web
        ports:
        - containerPort: 8080
          name: web
